### ISSUE TITLE
How do you store the merkle tree?

### ISSUE THREAD

**Issue by lurais** [solana-developers/compressed-nfts#1]
How do you store the merkle tree? How do you store it in  a ledger?

**Comment by lurais** [comment]
> Merkle 树由树叶组成，树叶中存储交易信息，通过索引所有使用 Merkle Tree 的交易，可以重新创建整棵树。

Is that means you won't store the real tree, and only just store the transactions ,If some one need the tree, they can build the tree by themselfs?

**Comment by ngundotra** [comment]
Yes exactly!

**Comment by nickfrosty** [comment]
I'm closing this since Noah answered so wonderfully :1st_place_medal:
