### ISSUE TITLE
fetchNFTsByCollection.ts script ( error : No results returned ) 

### ISSUE THREAD

**Issue by bubu59** [solana-developers/compressed-nfts#3]
Hi @nickfrosty , I have successfully ran the scripts about 2 weeks ago following the order of scripts as mentioned in the README. including fetching nfts by collection. However, when I ran it again today, ie `fetchNFTsByCollection` and `fetchNFTsByOwner`, both throws an error saying that no results returned.. Any idea why this might be the case ? 

<img width="778" alt="Screenshot 2023-05-15 at 12 45 40 PM" src="https://github.com/solana-developers/compressed-nfts/assets/74093051/2a412fa8-68c8-4a8e-a15f-212c0519a38e">

**Comment by nickfrosty** [comment]
I have a few questions for you:

- What rpc provider are you using?
- what network are you connecting too?
- can you give the collection address you are checking?

**Comment by bubu59** [comment]
1/2) Helius rpc provider ( devnet ) 
3) Collection mint: CkDaXYrAPu5LoZJTkDr45eR3bXKnHzoUxhyJJozeCpT1

**Comment by nickfrosty** [comment]
It seems like their was a bug on the RPC's parser and within the code in this repo. Both have been fixed :)
Specifically with sending a `page` value of 0. It should have been >=1.
Thanks for bringing this up :) I'm going to close this issue.
