### ISSUE TITLE
Help for Newbie's

### ISSUE THREAD

**Issue by 01DEXY** [solana-developers/compressed-nfts#5]
Please help with detailed guide,if you can ... for example : 

1. download Visual Studio Code
2. download extensions for normal work
3. create new file ,and type code 
npm.. and other

Maybe it's dumb question ,but please help me step by step 🥹🥹🥹

**Comment by buffalojoec** [comment]
Hey this stuff is pretty readily available on the web and Solana Stack Exchange.

Downloading VS Code and extensions has nothing to do with compressed NFTs
