### ISSUE TITLE
Collection can be unverified

### ISSUE THREAD

**Issue by nelsontky** [solana-developers/compressed-nfts#6]
Correct me if I am wrong, but it is possible for compressed NFTs to have their collections unverified right? It that's the case then this comment is wrong:
https://github.com/solana-developers/compressed-nfts/blob/53cc86de9bbe3048fff84ee4c0e968e1cee18eae/scripts/verifyCreator.ts#L169

Unverification of collection NFT:
https://github.com/metaplex-foundation/metaplex-program-library/blob/eb000db66feb258df1206ba257c30a9c54c8fcfc/bubblegum/program/src/lib.rs#L1081

**Comment by hauchu1998** [comment]
I think the cNFT can be unverified. However, the `mintToCollectionV1` will set the verified to `true` automatically. If you want to  make the cNFT unverified, you have to `mintToCollectionV1 `first then call the `unverifyCollection` insturction to make it unverified.

**Comment by nelsontky** [comment]
Yea thanks for the reply, realized that under the context of the script the comment would have made sense. Thanks for the clarification!

**Comment by nickfrosty** [comment]
Sorry for the late response, but yes! Everything @hauchu1998 said is correct.
